# frozen_string_literal: true

ruby '3.0.3'
source 'https://rubygems.org'
gem 'activerecord', '~> 7.0'
gem 'dotenv', '~> 2.8'
gem 'pg', '~> 1.4'
gem 'rack', '~> 2.2'
gem 'rack-test', '~> 2.0'
gem 'rspec', '~> 3.11'
gem 'sinatra', '~> 2.2'
gem 'webrick', '~> 1.7'

group :development, :test do
  gem 'rubocop', '~> 1.73.2', require: false
end
